export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOADING = 'LOADING';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const ADD_NEW_RIDE_CLIENT_SUCCESS = 'ADD_NEW_RIDE_CLIENT_SUCCESS';
export const ADD_NEW_RIDE_CLIENT_ERROR = 'ADD_NEW_RIDE_CLIENT_ERROR';
